'use strict';

const assert = require('node:assert/strict');
const test = require('node:test');
const { toPostgresSql } = require('../server/db/postgres');

test('PostgreSQL adapter converts positional placeholders without changing literals', () => {
  assert.equal(
    toPostgresSql("SELECT '?' AS literal, email FROM users WHERE id = ? AND note = 'what?'"),
    "SELECT '?' AS literal, email FROM users WHERE id = $1 AND note = 'what?'"
  );
});

test('PostgreSQL adapter converts SQLite schema primitives and clock functions', () => {
  const sql = toPostgresSql(
    "CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, created_at TEXT DEFAULT (datetime('now')), updated_at INTEGER DEFAULT (unixepoch()))"
  );
  assert.match(sql, /INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
  assert.match(sql, /to_char\(CURRENT_TIMESTAMP AT TIME ZONE 'UTC'/);
  assert.match(sql, /EXTRACT\(EPOCH FROM CURRENT_TIMESTAMP\)::integer/);
});

test('PostgreSQL adapter preserves date expressions used by retention and status queries', () => {
  assert.match(toPostgresSql("SELECT date('now', ?) AS day"), /CURRENT_DATE \+ \(\$1\)::interval/);
  assert.match(toPostgresSql("SELECT date(checked_at, 'unixepoch') AS day"), /to_timestamp\(checked_at\)/);
  assert.match(
    toPostgresSql('UPDATE t SET outage_seconds = MAX(0, ? - started_at)'),
    /GREATEST\(0, \$1 - started_at\)/
  );
  assert.match(toPostgresSql('ALTER TABLE users ADD COLUMN avatar_url TEXT'), /ADD COLUMN IF NOT EXISTS avatar_url/);
});

test('PostgreSQL adapter converts INSERT OR IGNORE and adds ids only to identity tables', () => {
  assert.equal(
    toPostgresSql('INSERT OR IGNORE INTO radar_events (radar_id) VALUES (?)'),
    'INSERT INTO radar_events (radar_id) VALUES ($1) ON CONFLICT DO NOTHING'
  );
  assert.equal(
    toPostgresSql('INSERT INTO users (email) VALUES (?)', { includeReturningId: true }),
    'INSERT INTO users (email) VALUES ($1) RETURNING id'
  );
  assert.equal(
    toPostgresSql('INSERT INTO watchlist (user_id, symbol) VALUES (?, ?)', { includeReturningId: true }),
    'INSERT INTO watchlist (user_id, symbol) VALUES ($1, $2)'
  );
});
