export const COLORS = [
  '#F59E0B',
  '#22c55e',
  '#06b6d4',
  '#ef4444',
  '#FBBF24',
  '#3b82f6',
  '#ec4899',
  '#f97316',
  '#84cc16',
  '#14b8a6',
  '#64748B',
];

export const SECTOR_ETFS = [
  {
    ticker: 'XLK',
    color: '#06b6d4',
    name: 'Technology',
    desc: 'Tech giants — software, hardware, semiconductors, and IT services',
    holdings: [
      { sym: 'AAPL', name: 'Apple Inc.', weight: '21.5%' },
      { sym: 'MSFT', name: 'Microsoft Corp.', weight: '20.8%' },
      { sym: 'NVDA', name: 'NVIDIA Corp.', weight: '6.2%' },
    ],
  },
  {
    ticker: 'XLF',
    color: '#10b981',
    name: 'Financials',
    desc: 'Banks, insurance companies, asset managers, and capital markets',
    holdings: [
      { sym: 'BRK.B', name: 'Berkshire Hathaway', weight: '14.1%' },
      { sym: 'JPM', name: 'JPMorgan Chase', weight: '10.5%' },
      { sym: 'V', name: 'Visa Inc.', weight: '7.8%' },
    ],
  },
  {
    ticker: 'XLV',
    color: '#ef4444',
    name: 'Health Care',
    desc: 'Pharma, biotech, medical devices, and health care providers',
    holdings: [
      { sym: 'LLY', name: 'Eli Lilly & Co.', weight: '11.8%' },
      { sym: 'UNH', name: 'UnitedHealth Group', weight: '9.5%' },
      { sym: 'JNJ', name: 'Johnson & Johnson', weight: '7.2%' },
    ],
  },
  {
    ticker: 'XLY',
    color: '#f59e0b',
    name: 'Consumer Discretionary',
    desc: 'Retail, autos, apparel, restaurants, and luxury goods',
    holdings: [
      { sym: 'AMZN', name: 'Amazon.com Inc.', weight: '22.3%' },
      { sym: 'TSLA', name: 'Tesla Inc.', weight: '14.6%' },
      { sym: 'HD', name: 'Home Depot Inc.', weight: '8.1%' },
    ],
  },
  {
    ticker: 'XLP',
    color: '#f97316',
    name: 'Consumer Staples',
    desc: 'Food, beverages, household products, and personal care',
    holdings: [
      { sym: 'PG', name: 'Procter & Gamble', weight: '14.8%' },
      { sym: 'COST', name: 'Costco Wholesale', weight: '11.2%' },
      { sym: 'KO', name: 'Coca-Cola Co.', weight: '9.5%' },
    ],
  },
  {
    ticker: 'XLE',
    color: '#84cc16',
    name: 'Energy',
    desc: 'Oil & gas exploration, production, refining, and equipment',
    holdings: [
      { sym: 'XOM', name: 'Exxon Mobil Corp.', weight: '22.7%' },
      { sym: 'CVX', name: 'Chevron Corp.', weight: '15.3%' },
      { sym: 'COP', name: 'ConocoPhillips', weight: '7.8%' },
    ],
  },
  {
    ticker: 'XLI',
    color: '#64748B',
    name: 'Industrials',
    desc: 'Aerospace, defense, machinery, construction, and logistics',
    holdings: [
      { sym: 'GE', name: 'GE Aerospace', weight: '8.9%' },
      { sym: 'CAT', name: 'Caterpillar Inc.', weight: '5.6%' },
      { sym: 'RTX', name: 'RTX Corp.', weight: '4.8%' },
    ],
  },
  {
    ticker: 'XLB',
    color: '#ec4899',
    name: 'Materials',
    desc: 'Chemicals, metals, mining, packaging, and construction materials',
    holdings: [
      { sym: 'LIN', name: 'Linde plc', weight: '17.2%' },
      { sym: 'SHW', name: 'Sherwin-Williams', weight: '9.1%' },
      { sym: 'FCX', name: 'Freeport-McMoRan', weight: '6.8%' },
    ],
  },
  {
    ticker: 'XLRE',
    color: '#0EA5E9',
    name: 'Real Estate',
    desc: 'REITs — commercial, residential, and specialized real estate',
    holdings: [
      { sym: 'PLD', name: 'Prologis Inc.', weight: '13.5%' },
      { sym: 'AMT', name: 'American Tower', weight: '9.8%' },
      { sym: 'EQIX', name: 'Equinix Inc.', weight: '7.6%' },
    ],
  },
  {
    ticker: 'XLU',
    color: '#14b8a6',
    name: 'Utilities',
    desc: 'Electric, gas, water utilities, and renewable energy producers',
    holdings: [
      { sym: 'NEE', name: 'NextEra Energy', weight: '14.9%' },
      { sym: 'SO', name: 'Southern Company', weight: '8.3%' },
      { sym: 'DUK', name: 'Duke Energy Corp.', weight: '7.1%' },
    ],
  },
  {
    ticker: 'XLC',
    color: '#3b82f6',
    name: 'Communication Services',
    desc: 'Telecom, media, entertainment, and interactive platforms',
    holdings: [
      { sym: 'META', name: 'Meta Platforms', weight: '23.1%' },
      { sym: 'GOOGL', name: 'Alphabet Inc.', weight: '22.4%' },
      { sym: 'NFLX', name: 'Netflix Inc.', weight: '5.8%' },
    ],
  },
  {
    ticker: 'SOXX',
    color: '#06b6d4',
    name: 'Semiconductors',
    desc: 'Chip designers, foundries, and semiconductor equipment makers',
    holdings: [
      { sym: 'NVDA', name: 'NVIDIA Corp.', weight: '10.2%' },
      { sym: 'AVGO', name: 'Broadcom Inc.', weight: '8.5%' },
      { sym: 'AMD', name: 'AMD Inc.', weight: '7.1%' },
    ],
  },
  {
    ticker: 'XOP',
    color: '#84cc16',
    name: 'Oil & Gas E&P',
    desc: 'Oil and gas exploration and production companies',
    holdings: [
      { sym: 'COP', name: 'ConocoPhillips', weight: '5.1%' },
      { sym: 'EOG', name: 'EOG Resources', weight: '4.9%' },
      { sym: 'PXD', name: 'Pioneer Natural', weight: '4.7%' },
    ],
  },
  {
    ticker: 'XTL',
    color: '#f59e0b',
    name: 'Telecom',
    desc: 'Wireless carriers, broadband providers, and telecom infrastructure',
    holdings: [
      { sym: 'T', name: 'AT&T Inc.', weight: '5.2%' },
      { sym: 'VZ', name: 'Verizon Comm.', weight: '4.9%' },
      { sym: 'TMUS', name: 'T-Mobile US', weight: '4.8%' },
    ],
  },
  {
    ticker: 'IGV',
    color: '#0891B2',
    name: 'Software',
    desc: 'Enterprise and consumer software, SaaS, and cloud platforms',
    holdings: [
      { sym: 'MSFT', name: 'Microsoft Corp.', weight: '9.4%' },
      { sym: 'CRM', name: 'Salesforce Inc.', weight: '5.1%' },
      { sym: 'ORCL', name: 'Oracle Corp.', weight: '4.8%' },
    ],
  },
];
